- name: Configure web servers
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: true
    - name: create directory structure for web documents
      file:
        path: /web/html
        state: directory
    - name: copy nginx conf file to server
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
    - name: create link to nginx config file to enable it
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: Generate index.html file from template
      template:
        src: templates/index.html.j2
        dest: /web/html/index.html

    - name: reload nginx service
      service:
        name: nginx
        state: reloaded
        enabled: true