- name: Setup Frontend Server
  hosts: server_role_frontend_server
  become: true
  gather_facts: yes
  roles:
    - server_role_frontend_server

- name: Setup Redis Server
  hosts: server_role_redis_server
  become: true
  gather_facts: yes
  roles:
    - server_role_redis_server